[project]
name = "rust-for-data-science"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.30.0",
    "matplotlib>=3.10.3",
    "maturin>=1.9.1",
    "numpy>=2.3.1",
    "py-spy>=0.4.0",
    "scikit-learn>=1.7.1",
]
